language: ruby

sudo: false

services:
  - redis
  - memcached

addons:
  postgresql: 9.3
  artifacts:
    paths:
    - log/

cache: bundler

sudo: false

rvm:
  - "2.0"
  - "2.1"

matrix:
  fast_finish: true

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create --trace'

script:
  - ./build.sh
